### ISSUE TITLE
Offers section: image capture, customization, data security

### ISSUE THREAD

**Issue by wycka0214** [front-end-by-rimantas/16-grupe-portfolio-leverage#22]
Offers section
- icon:
       * Image Capture (camera icon)
       * Customization (pencil-square)
       * Data Security (lock) 
- text (Lorem)

**Comment by belauzas** [comment]
@wycka0214  Čia kol kas turbūt per klaidą "Review in progress"?

**Comment by belauzas** [comment]
Plius, pavadinimas vien didžiosiomis raidėmis... gal kiek per stipriai 😅

**Comment by belauzas** [comment]
Plius plius, nesimato atskiro branch šiai užduočiai 🤔 gal netyčia ji local'i?

**Comment by wycka0214** [comment]
sutvarkysiu 😔

**Comment by wycka0214** [comment]
branch: customization
lyg yra

**Comment by belauzas** [comment]
Plius plius plius, iš pavadinimo ir aprašymo nelabai aišku:
- apie kurių paveiksliukų caption eina kalba
- kieno customization čia turimas omeny
- kas yra ir kaip suprasti data security
Turbūt reikėtų truputi patikslinti aprašymą 🤔

Dėl branch - sorry, nepastebėjau 😥

**Comment by belauzas** [comment]
Ką tik pastebėjau, jog tai https://github.com/front-end-by-rimantas/16-grupe-portfolio-leverage/issues/6 dublikatas 😅
Uždariau.
