### ISSUE TITLE
Layout: display grid 12 collums

### ISSUE THREAD

**Issue by wycka0214** [front-end-by-rimantas/16-grupe-portfolio-leverage#30]
- Display grid:
**12 collums** grid, and the classes belonging to it
- responsive by 12col

**Comment by evelinao1** [comment]
Bet gal nebūtina su jų forma (https://getbootstrap.com/docs/4.0/layout/grid/) daryti, gal tiesiog galima ja remtis ir patiems rašyti, kaip Rimantas darė

**Comment by wycka0214** [comment]
patasiau uzduoti. Galim nukopint nuo Rimanto projecto :)

**Comment by evelinao1** [comment]
Ir gal dar responsve kartu reiktų padaryt prie tos užduoties?

**Comment by wycka0214** [comment]
Sutinku, irasiau task`a
